export const dtf = [
    {
        id: 1,
        titulo: "Tinta para DTF",
        img: "/images/Dtf/tinta.png",
        imgtop: "/images/Dtf/1lt.png",
        subtitulo: "Para uso en impresora Direct To Film.",
        subtitulo1: "Colores intensos y vibrantes, tinta blanca con excelente elasticidad.",
        clase: "ul-azul",
        section: "tinta-dtf",
        line: "",
        a1: "Dorso impreso",
        a2: "Máxima descarga",
        a3: "Secado rápido",
        b1: "para identificar fácilmente el lado blanco imprimible.",
        b2: "descarga de tinta sin igual, logrando resultados con colores súper nítidos.",
        b3: "minimiza el riesgo de manchas o borrones y da mayor eficiencia.",
        c1: "/images/Dtf/c1.png",
        c2: "/images/Dtf/c2.png",
        c3: "/images/Dtf/c3.png",

    },
    {
        id: 2,
        titulo: "Film para DTF",
        img: "/images/Dtf/rollo.png",
        subtitulo: "Para uso en impresora Direct To Film.",
        clase: "ul-subli",
        section: "film-dtf",
        line: "line",
        product: "Rollo",
        a1: "Dorso impreso",
        a2: "No se marca",
        a3: "Secado rápido",
        b1: "para identificar fácilmente el lado blanco imprimible.",
        b2: "no deja “camino de hormiga” en tus impresiones.",
        b3: "minimiza el riesgo de manchas o borrones y da mayor eficiencia.",
        c1: "/images/Dtf/c1.1.png",
        c2: "/images/Dtf/c2.1.png",
        c3: "/images/Dtf/c3.1.png",

    },
    {
        id: 3,
        titulo: "Polvo para DTF",
        img: "/images/Dtf/polvo.png",
        subtitulo: "Para uso en impresora Direct To Film.",
        clase: "ul-subli",
        section: "polvo-dtf",
        line: "line",
        a1: "Alta descarga de tinta",
        a2: "Impresión de plenos",
        a3: "Para impresora A4 y A3",
        b1: "logrando una óptima definición en tus trabajos de sublimación.",
        b2: "soporta grandes cargas de tinta, permite reproducir negros profundos y colores vivos.",
        b3: "Los tamaños del rollo son compatibles con ambos formatos de impresoras.",
        c1: "/images/Dtf/c2.1.png",
        c2: "/images/Dtf/c2.2.png",
        c3: "/images/Dtf/c3.2.png",


    },

]
