export const dtf = [
    {
        id: 1,
        titulo: "Tinta para DTF",
        img: "/images/Dtf/tinta.png",
        imgtop: "/images/Dtf/1lt.png",
        subtitulo: "Para uso en impresora Direct To Film.",
        subtitulo1: "Colores intensos y vibrantes, tinta blanca con excelente elasticidad.",
        clase: "ul-azul",
        section: "tinta-dtf",
        line: "",
        a1: "Cubritiva",
        a2: "Resistente",
        a3: "Estampado sobre",
        b1: "excelente adhesión al textil.",
        b2: "a la decoloración, el agretamiento, el pelado, y a los lavados",
        b3: "gran variedad de telas y todos los colores",
        c1: "/images/Dtf/c1.png",
        c2: "/images/Dtf/c2.png",
        c3: "/images/Dtf/c3.png",

    },
    {
        id: 2,
        titulo: "Film para DTF",
        img: "/images/Dtf/rollo.png",
        subtitulo: "Para uso en impresora Direct To Film.",
        clase: "ul-subli",
        section: "film-dtf",
        line: "line",
        product: "Rollo",
        a1: "Estabilidad",
        a2: "Pelado en frio",
        a3: "Elasticidad",
        b1: "de dimensiones. No se dobla ni deforma con el calor.",
        b2: "permitiendo una transferencia precisa y segura del diseño",
        b3: "tacto suave de los transfer y excelente solidez al lavado",
        c1: "/images/Dtf/c1.1.png",
        c2: "/images/Dtf/c2.1.png",
        c3: "/images/Dtf/c3.1.png",

    },
    {
        id: 3,
        titulo: "Polvo para DTF",
        img: "/images/Dtf/polvo.png",
        subtitulo: "Para uso en impresora Direct To Film.",
        clase: "ul-subli",
        section: "polvo-dtf",
        line: "line",
        a1: "Alta absorción",
        a2: "Transferencia suave",
        a3: "Resistencia",
        b1: "de tintas, mejor efecto de impresión. Absorción uniforme.",
        b2: "y curado rápidopara un fácil enrollado y almacenamiento",
        b3: "a la temperatura y baja electricidad estática",
        c1: "/images/Dtf/c2.1.png",
        c2: "/images/Dtf/c2.2.png",
        c3: "/images/Dtf/c3.2.png",


    },

]
