export const magneticos = [
    {
        id: 1,
        titulo: "Fast Dry",
        img: "/images/fotografico/magnetico1.png",
        imgtop: "/images/subli/papeles/imgtop.png",
        subtitulo: "Para uso en impresoras inkjet con tinta de sublimación.",
        a1: "Dorso impreso",
        a2: "Máxima descarga",
        a3: "Secado rápido",
        b1: "para identificar fácilmente el lado blanco imprimible.",
        b2: "descarga de tinta sin igual, logrando resultados con colores súper nítidos.",
        b3: "minimiza el riesgo de manchas o borrones y da mayor eficiencia.",
        c1: "/images/subli/papeles/c1.png",
        c2: "/images/subli/papeles/c2.png",
        c3: "/images/subli/papeles/c3.png",
        d1: "/images/subli/papeles/d1.png",
        d2: "/images/subli/papeles/d2.png",
        d3: "/images/subli/papeles/d3.png",
        d4: "/images/subli/papeles/d4.png",
        d5: "/images/subli/papeles/d5.png",

    },
    {
        id: 2,
        titulo: "Instant Dry",
        img: "/images/fotografico/magnetico2.png",
        imgtop: "/images/subli/papeles/imgtop.png",
        subtitulo: "Para uso en impresoras inkjet con tinta de sublimación.",
        a1: "Dorso impreso",
        a2: "No se marca",
        a3: "Secado rápido",
        b1: "para identificar fácilmente el lado blanco imprimible.",
        b2: "no deja “camino de hormiga” en tus impresiones.",
        b3: "minimiza el riesgo de manchas o borrones y da mayor eficiencia.",
        c1: "/images/subli/papeles/c1.png",
        c2: "/images/subli/papeles/c2.1.png",
        c3: "/images/subli/papeles/c3.png",
        d1: "/images/subli/papeles/d1.1.png",
        d2: "/images/subli/papeles/d2.1.png",
        d3: "/images/subli/papeles/d3.1.png",
        d4: "/images/subli/papeles/d4.1.png",
        d5: "/images/subli/papeles/d5.1.png",

    }
]

export const autoadhesivos = [
    {
        id: 1,
        titulo: "Fast Dry",
        img: "/images/fotografico/autoadhesivo1.png",
        imgtop: "/images/subli/papeles/imgtop.png",
        subtitulo: "Para uso en impresoras inkjet con tinta de sublimación.",
        a1: "Dorso impreso",
        a2: "Máxima descarga",
        a3: "Secado rápido",
        b1: "para identificar fácilmente el lado blanco imprimible.",
        b2: "descarga de tinta sin igual, logrando resultados con colores súper nítidos.",
        b3: "minimiza el riesgo de manchas o borrones y da mayor eficiencia.",
        c1: "/images/subli/papeles/c1.png",
        c2: "/images/subli/papeles/c2.png",
        c3: "/images/subli/papeles/c3.png",
        d1: "/images/subli/papeles/d1.png",
        d2: "/images/subli/papeles/d2.png",
        d3: "/images/subli/papeles/d3.png",
        d4: "/images/subli/papeles/d4.png",
        d5: "/images/subli/papeles/d5.png",

    },
    {
        id: 2,
        titulo: "Instant Dry",
        img: "/images/fotografico/autoadhesivo2.png",
        imgtop: "/images/subli/papeles/imgtop.png",
        subtitulo: "Para uso en impresoras inkjet con tinta de sublimación.",
        a1: "Dorso impreso",
        a2: "No se marca",
        a3: "Secado rápido",
        b1: "para identificar fácilmente el lado blanco imprimible.",
        b2: "no deja “camino de hormiga” en tus impresiones.",
        b3: "minimiza el riesgo de manchas o borrones y da mayor eficiencia.",
        c1: "/images/subli/papeles/c1.png",
        c2: "/images/subli/papeles/c2.1.png",
        c3: "/images/subli/papeles/c3.png",
        d1: "/images/subli/papeles/d1.1.png",
        d2: "/images/subli/papeles/d2.1.png",
        d3: "/images/subli/papeles/d3.1.png",
        d4: "/images/subli/papeles/d4.1.png",
        d5: "/images/subli/papeles/d5.1.png",

    }
]

export const resinados = [
    {
        id: 1,
        titulo: "Fast Dry",
        img: "/images/fotografico/resinado1.png",
        imgtop: "/images/subli/papeles/imgtop.png",
        subtitulo: "Para uso en impresoras inkjet con tinta de sublimación.",
        a1: "Resalta los colores",
        a2: "Versatilidad",
        a3: "Lugares luminosos",
        b1: "Su acabado brillante crea un efecto visual impactante.",
        b2: "fotografía, proyectos creativos, publicidad, tarjetas, álbumes y más.",
        b3: "ideal para fotografías expuestas en lugares luminosos. Propenso a reflejos.",
        c1: "/images/fotografico/c1.png",
        c2: "/images/fotografico/c3.png",
        c3: "/images/fotografico/c2.png",

    },
    {
        id: 2,
        titulo: "Instant Dry",
        img: "/images/fotografico/resinado2.png",
        imgtop: "/images/subli/papeles/imgtop.png",
        subtitulo: "Para uso en impresoras inkjet con tinta de sublimación.",
        a1: "Resalta los colores",
        a2: "Retrato y fotografía",
        a3: "Proyectos artísticos",
        b1: "Su acabado brillante crea un efecto visual impactante.",
        b2: "ideal para fotos que incluyan tonos de piel, dando una apariencia natural.",
        b3: "una ligera rugosidad brinda profundidad y una sensación táctil a la imagen.",
        c1: "/images/fotografico/c1.png",
        c2: "/images/fotografico/c3.png",
        c3: "/images/fotografico/c3.1.png",

    },

    {
        id: 3,
        titulo: "Instant Dry",
        img: "/images/fotografico/resinado3.png",
        imgtop: "/images/subli/papeles/imgtop.png",
        subtitulo: "Para uso en impresoras inkjet con tinta de sublimación.",
        a1: "Gran Nitidez ",
        a2: "Variedad de usos",
        a3: "Apariencia elegante",
        b1: "reproducción precisa de colores y tonos, con una ligera reflectividad. ",
        b2: "fotografía, impresiones comerciales, etc. Reduce reflejos y resalta detalles.",
        b3: "Ideal para exponer en lugares donde la luz pueda causar problemas de reflejos.",
        c1: "/images/fotografico/c1.png",
        c2: "/images/fotografico/c3.png",
        c3: "/images/fotografico/c3.1.png",

    }
]

