export const magneticos = [
    {
        id: 1,
        titulo: "Fast Dry",
        img: "/images/subli/papeles/img1.png",
        imgtop: "/images/subli/papeles/imgtop.png",
        subtitulo: "Para uso en impresoras inkjet con tinta de sublimación.",
        a1: "Dorso impreso",
        a2: "Máxima descarga",
        a3: "Secado rápido",
        b1: "para identificar fácilmente el lado blanco imprimible.",
        b2: "descarga de tinta sin igual, logrando resultados con colores súper nítidos.",
        b3: "minimiza el riesgo de manchas o borrones y da mayor eficiencia.",
        c1: "/images/subli/papeles/c1.png",
        c2: "/images/subli/papeles/c2.png",
        c3: "/images/subli/papeles/c3.png",
        d1: "/images/subli/papeles/d1.png",
        d2: "/images/subli/papeles/d2.png",
        d3: "/images/subli/papeles/d3.png",
        d4: "/images/subli/papeles/d4.png",
        d5: "/images/subli/papeles/d5.png",

    },
    {
        id: 2,
        titulo: "Instant Dry",
        img: "/images/subli/papeles/img1.png",
        imgtop: "/images/subli/papeles/imgtop.png",
        subtitulo: "Para uso en impresoras inkjet con tinta de sublimación.",
        a1: "Dorso impreso",
        a2: "No se marca",
        a3: "Secado rápido",
        b1: "para identificar fácilmente el lado blanco imprimible.",
        b2: "no deja “camino de hormiga” en tus impresiones.",
        b3: "minimiza el riesgo de manchas o borrones y da mayor eficiencia.",
        c1: "/images/subli/papeles/c1.png",
        c2: "/images/subli/papeles/c2.1.png",
        c3: "/images/subli/papeles/c3.png",
        d1: "/images/subli/papeles/d1.1.png",
        d2: "/images/subli/papeles/d2.1.png",
        d3: "/images/subli/papeles/d3.1.png",
        d4: "/images/subli/papeles/d4.1.png",
        d5: "/images/subli/papeles/d5.1.png",

    }
]

export const autoadhesivos = [
    {
        id: 1,
        titulo: "Fast Dry",
        img: "/images/subli/papeles/img1.png",
        imgtop: "/images/subli/papeles/imgtop.png",
        subtitulo: "Para uso en impresoras inkjet con tinta de sublimación.",
        a1: "Dorso impreso",
        a2: "Máxima descarga",
        a3: "Secado rápido",
        b1: "para identificar fácilmente el lado blanco imprimible.",
        b2: "descarga de tinta sin igual, logrando resultados con colores súper nítidos.",
        b3: "minimiza el riesgo de manchas o borrones y da mayor eficiencia.",
        c1: "/images/subli/papeles/c1.png",
        c2: "/images/subli/papeles/c2.png",
        c3: "/images/subli/papeles/c3.png",
        d1: "/images/subli/papeles/d1.png",
        d2: "/images/subli/papeles/d2.png",
        d3: "/images/subli/papeles/d3.png",
        d4: "/images/subli/papeles/d4.png",
        d5: "/images/subli/papeles/d5.png",

    },
    {
        id: 2,
        titulo: "Instant Dry",
        img: "/images/subli/papeles/img1.png",
        imgtop: "/images/subli/papeles/imgtop.png",
        subtitulo: "Para uso en impresoras inkjet con tinta de sublimación.",
        a1: "Dorso impreso",
        a2: "No se marca",
        a3: "Secado rápido",
        b1: "para identificar fácilmente el lado blanco imprimible.",
        b2: "no deja “camino de hormiga” en tus impresiones.",
        b3: "minimiza el riesgo de manchas o borrones y da mayor eficiencia.",
        c1: "/images/subli/papeles/c1.png",
        c2: "/images/subli/papeles/c2.1.png",
        c3: "/images/subli/papeles/c3.png",
        d1: "/images/subli/papeles/d1.1.png",
        d2: "/images/subli/papeles/d2.1.png",
        d3: "/images/subli/papeles/d3.1.png",
        d4: "/images/subli/papeles/d4.1.png",
        d5: "/images/subli/papeles/d5.1.png",

    }
]

export const resinados = [
    {
        id: 1,
        titulo: "Fast Dry",
        img: "/images/subli/papeles/img1.png",
        imgtop: "/images/subli/papeles/imgtop.png",
        subtitulo: "Para uso en impresoras inkjet con tinta de sublimación.",
        a1: "Dorso impreso",
        a2: "Máxima descarga",
        a3: "Secado rápido",
        b1: "para identificar fácilmente el lado blanco imprimible.",
        b2: "descarga de tinta sin igual, logrando resultados con colores súper nítidos.",
        b3: "minimiza el riesgo de manchas o borrones y da mayor eficiencia.",
        c1: "/images/subli/papeles/c1.png",
        c2: "/images/subli/papeles/c2.png",
        c3: "/images/subli/papeles/c3.png",
        d1: "/images/subli/papeles/d1.png",
        d2: "/images/subli/papeles/d2.png",
        d3: "/images/subli/papeles/d3.png",
        d4: "/images/subli/papeles/d4.png",
        d5: "/images/subli/papeles/d5.png",

    },
    {
        id: 2,
        titulo: "Instant Dry",
        img: "/images/subli/papeles/img1.png",
        imgtop: "/images/subli/papeles/imgtop.png",
        subtitulo: "Para uso en impresoras inkjet con tinta de sublimación.",
        a1: "Dorso impreso",
        a2: "No se marca",
        a3: "Secado rápido",
        b1: "para identificar fácilmente el lado blanco imprimible.",
        b2: "no deja “camino de hormiga” en tus impresiones.",
        b3: "minimiza el riesgo de manchas o borrones y da mayor eficiencia.",
        c1: "/images/subli/papeles/c1.png",
        c2: "/images/subli/papeles/c2.1.png",
        c3: "/images/subli/papeles/c3.png",
        d1: "/images/subli/papeles/d1.1.png",
        d2: "/images/subli/papeles/d2.1.png",
        d3: "/images/subli/papeles/d3.1.png",
        d4: "/images/subli/papeles/d4.1.png",
        d5: "/images/subli/papeles/d5.1.png",

    },

    {
        id: 3,
        titulo: "Instant Dry",
        img: "/images/subli/papeles/img1.png",
        imgtop: "/images/subli/papeles/imgtop.png",
        subtitulo: "Para uso en impresoras inkjet con tinta de sublimación.",
        a1: "Dorso impreso",
        a2: "No se marca",
        a3: "Secado rápido",
        b1: "para identificar fácilmente el lado blanco imprimible.",
        b2: "no deja “camino de hormiga” en tus impresiones.",
        b3: "minimiza el riesgo de manchas o borrones y da mayor eficiencia.",
        c1: "/images/subli/papeles/c1.png",
        c2: "/images/subli/papeles/c2.1.png",
        c3: "/images/subli/papeles/c3.png",
        d1: "/images/subli/papeles/d1.1.png",
        d2: "/images/subli/papeles/d2.1.png",
        d3: "/images/subli/papeles/d3.1.png",
        d4: "/images/subli/papeles/d4.1.png",
        d5: "/images/subli/papeles/d5.1.png",

    }
]

