export const transfers = [
    {
        id: 1,
        titulo: "Textil Claro",
        img: "/images/transfer/transfer1.png",
        imgtop: "/images/subli/papeles/imgtop.png",
        subtitulo: "Para uso con tintas pigmentadas.",
        a1: "Hogareño y comercial",
        a2: "Corte versátil",
        a3: "Uso destacado",
        b1: "se puede adherir con plancha doméstica o prensa plana.",
        b2: "se puede cortar con plotter o a mano.",
        b3: "en textiles de algodón blancos.",
        c1: "/images/transfer/c1.png",
        c2: "/images/transfer/c2.png",
        c3: "/images/transfer/c3.png",
    },
    {
        id: 2,
        titulo: "Textil Oscuro",
        img: "/images/subli/papeles/img1.png",
        imgtop: "/images/subli/papeles/imgtop.png",
        subtitulo: "Para uso en impresoras inkjet con tinta de sublimación.",
        a1: "Hogareño y comercial",
        a2: "Corte versátil",
        a3: "Uso destacado",
        b1: "se puede adherir con plancha doméstica o prensa plana.",
        b2: "se puede cortar con plotter o a mano.",
        b3: "en textiles de algodón blancos.",
        c1: "/images/transfer/c1.png",
        c2: "/images/transfer/c2.png",
        c3: "/images/transfer/c3.png",

    }
]